adjective1 = input("Enter an adjective (description of something): ")
noun1 = input("Enter a noun (person):")
adjective2 = input("Enter an adjective :")
verb1 = input("Enter a verb ending with 'ing'")
adjective3 = input("Enter an adjective:")

print(f"today i went to an {adjective1} zoo.")
print(f"In an exhibit i saw a {noun1}")
print(f"{noun1} was {adjective2} and {verb1}")
print(f"I was {adjective3}!")